name: CI
on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
 group: ${{ github.head_ref || github.run_id }}
 cancel-in-progress: true

jobs:
  a:
    runs-on: ubuntu-latest
    steps:
    - run: exit 0

  b:
    runs-on: ubuntu-latest
    steps:
    - run: exit 1

  all:
    if: always()
    needs: [a, b]
    runs-on: ubuntu-latest
    steps:
    - run: |
        # Test all dependencies for success/failure
        set -x
        success="${{ contains(needs.*.result, 'success') }}"
        fail="${{ contains(needs.*.result, 'failure') }}"
        set +x

        # Test whether success/fail variables contain sane values
        if [[ "${success}" != "true" && "${success}" != "false" ]]; then exit 1; fi
        if [[ "${fail}"    != "true" && "${fail}"    != "false" ]]; then exit 1; fi

        # We want to fail if one or more dependencies fail. For safety, we introduce
        # a second check: if no dependencies succeeded something weird is going on.
        if [[ "${fail}" == "true" || "${success}" == "false" ]]; then
          echo "One or more dependency failed, or no dependency succeeded."
          exit 1
        fi

        exit 0
